site_name: The ML.ENERGY Data & Toolkit
site_url: https://ml.energy/data
site_description: Datasets published by ML.ENERGY and toolkits for working with them.

repo_name: ml-energy/data
repo_url: https://github.com/ml-energy/data

copyright: Copyright &copy; 2026 ML.ENERGY

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/favicon/favicon.ico
  icon:
    logo: octicons/database-24
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Light mode
  features:
    - announce.dismiss

nav:
  - Home: index.md
  - Toolkit Guide: guide.md
  - API Reference:
      - Records: api/records.md
      - Modeling: api/modeling.md

plugins:
  - search
  - htmlproofer
  - social:
      enabled: !ENV [BUILD_SOCIAL_CARD, false]
      cards_dir: assets/img/social
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            members_order: source
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: !ENV SITE_ANALYTICS
    property: G-C013T57GV2
